# Generated by Django 4.2.2 on 2023-06-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
